pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"

  - bash: pip install -r requirements.txt
    displayName: "Install requirements"

  - bash: |
      pip install pytest-azurepipelines
      python -m pytest --junitxml=junit/unit-test.xml
    displayName: pytest

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "junit/*.xml"
    condition: succeededOrFailed()
